[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
# runner = 'riscv32-unknown-elf-gdb -x openocd.gdb'
linker = "riscv32-unknown-elf-gcc"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]
